version: '3'
services:
  web:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8081:8081"
    env_file: web.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
